### ISSUE TITLE
High Level Requirements for Observation Framework

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpc-test-suite#1]
On the landing page it stated that:
PC with Docker to setup the Test Runner and Observation Framework (Linux is preferred for production, but Windows and macOS are supported as well)

Observation Framework not require dokcer to set up and also is MUST be installed and run outside the docker.

**Comment by louaybassbouss** [comment]
@yanj-github  for some reason I missed the notification about this issue. It is fine to remove "Docker"?

**Comment by yanj-github** [comment]
@louaybassbouss How about:

PC with Docker to setup the Test Runner (Linux
is preferred for production, but Windows and macOS are supported as
well)

Observation Framework to be setup on the same PC and outside of Docker

**Comment by louaybassbouss** [comment]
> @louaybassbouss How about:
> 
> PC with Docker to setup the Test Runner (Linux is preferred for production, but Windows and macOS are supported as well)
> 
> Observation Framework to be setup on the same PC and outside of Docker

Thanks @yanj-github  LGTM

**Comment by louaybassbouss** [comment]
@yanj-github  feel free to close this issue if you are happy with the latest change.

**Comment by yanj-github** [comment]
LGTM closing issue.

**Comment by cta-source** [comment]
I know this is closed, but:

> PC with Docker to setup the Test Runner (Linux is preferred for production, 
> but Windows and macOS are supported as well)

I'm not sure about the word "supported". Our "support" doesn't include actual support staff. Maybe, "but Windows and macOS have been tested and work as well" ?

**Comment by louaybassbouss** [comment]
> I know this is closed, but:
> 
> > PC with Docker to setup the Test Runner (Linux is preferred for production,
> > but Windows and macOS are supported as well)
> 
> I'm not sure about the word "supported". Our "support" doesn't include actual support staff. Maybe, "but Windows and macOS have been tested and work as well" ?

Thanks @cta-source  fully agree I just changed it on the page :)
